#!/bin/bash
# =============================================================
# nginx-setup/nginx.sh
# Sets up Nginx reverse proxy with Basic Auth and optional SSL.
# Called by install.sh — all config via env vars.
# =============================================================
set -euo pipefail

SELLER_NAME="${SELLER_NAME:-seller1}"
CHROME_PORT="${CHROME_PORT:-3000}"
API_PORT="${API_PORT:-8787}"
CHROME_USER="${CHROME_USER:-admin}"
CHROME_PASS="${CHROME_PASS:?CHROME_PASS is required}"
SUBDOMAIN="${SUBDOMAIN:?SUBDOMAIN is required}"

if ! [[ "$SELLER_NAME" =~ ^[a-z0-9][a-z0-9_-]{0,31}$ ]]; then
  echo "ERROR: SELLER_NAME must match ^[a-z0-9][a-z0-9_-]{0,31}$"
  exit 1
fi

if ! [[ "$CHROME_PORT" =~ ^[0-9]+$ ]] || (( CHROME_PORT < 1 || CHROME_PORT > 65535 )); then
  echo "ERROR: CHROME_PORT must be between 1 and 65535"
  exit 1
fi

if ! [[ "$API_PORT" =~ ^[0-9]+$ ]] || (( API_PORT < 1 || API_PORT > 65535 )); then
  echo "ERROR: API_PORT must be between 1 and 65535"
  exit 1
fi

is_valid_subdomain() {
  local domain="$1" label tld idx
  [[ -n "$domain" && ${#domain} -le 253 ]] || return 1
  [[ "$domain" != .* && "$domain" != *. ]] || return 1
  [[ "$domain" != *..* ]] || return 1

  IFS='.' read -r -a labels <<< "$domain"
  (( ${#labels[@]} >= 2 )) || return 1

  for label in "${labels[@]}"; do
    [[ ${#label} -ge 1 && ${#label} -le 63 ]] || return 1
    [[ "$label" =~ ^[A-Za-z0-9-]+$ ]] || return 1
    [[ "$label" != -* && "$label" != *- ]] || return 1
  done

  idx=$((${#labels[@]} - 1))
  tld="${labels[$idx]}"
  [[ ${#tld} -ge 2 ]] || return 1
}

if ! is_valid_subdomain "$SUBDOMAIN"; then
  echo "ERROR: SUBDOMAIN must be a valid domain like chrome1.example.com"
  exit 1
fi

NGINX_AVAIL="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
CONF_NAME="${SELLER_NAME}-chrome"
HTPASSWD_DIR="/etc/nginx/htpasswd"
HTPASSWD_FILE="${HTPASSWD_DIR}/${SELLER_NAME}"

echo ""
echo "======================================"
echo " [nginx-setup] $SELLER_NAME"
echo " Subdomain : $SUBDOMAIN"
echo " Port      : $CHROME_PORT"
echo " API Port  : $API_PORT"
echo "======================================"
echo ""

# ─── Ensure nginx + apache2-utils installed ──────────────────
if ! command -v nginx &>/dev/null || ! command -v htpasswd &>/dev/null; then
  apt-get update -y -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx apache2-utils
fi
systemctl enable --now nginx

# ─── Basic Auth ──────────────────────────────────────────────
echo "Configuring Basic Auth..."
mkdir -p "$HTPASSWD_DIR"
htpasswd -cb "$HTPASSWD_FILE" "$CHROME_USER" "$CHROME_PASS"
chmod 640 "$HTPASSWD_FILE"
chown root:www-data "$HTPASSWD_FILE"

# ─── Nginx config ────────────────────────────────────────────
echo "Writing Nginx config → $NGINX_AVAIL/$CONF_NAME"
cat > "$NGINX_AVAIL/$CONF_NAME" <<NGINX
# ── ${SELLER_NAME} Chrome Browser VM ─────────────────────────
# Generated by chromium-fleet — do not edit manually.
# Subdomain : ${SUBDOMAIN}
# Port      : ${CHROME_PORT}

server {
    listen 80;
    listen [::]:80;
    server_name ${SUBDOMAIN};

    # ── Basic Auth ────────────────────────────────────────────
    auth_basic           "Chromium — ${SELLER_NAME}";
    auth_basic_user_file ${HTPASSWD_FILE};

    # ── Security headers ──────────────────────────────────────
    add_header X-Frame-Options          "SAMEORIGIN"                always;
    add_header X-Content-Type-Options   "nosniff"                   always;
    add_header X-XSS-Protection         "1; mode=block"             always;
    add_header Referrer-Policy          "no-referrer-when-downgrade" always;

    # ── Logging (per-seller) ─────────────────────────────────
    access_log /var/log/nginx/${SELLER_NAME}-chrome-access.log;
    error_log  /var/log/nginx/${SELLER_NAME}-chrome-error.log warn;

    # ── Proxy → Chromium (KasmVNC / noVNC WebSocket) ─────────
    location / {
        proxy_pass          http://127.0.0.1:${CHROME_PORT};

        proxy_http_version  1.1;
        proxy_set_header    Upgrade           \$http_upgrade;
        proxy_set_header    Connection        "upgrade";

        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;

        # Long timeouts for persistent WebSocket sessions
        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;
        proxy_connect_timeout   60s;

        proxy_buffering     off;
        proxy_buffer_size   128k;
        proxy_buffers       4 256k;
    }

    # Live monitoring stream (SSE) with long-lived connection settings
    location = /api/v1/monitor/stream {
        proxy_pass          http://127.0.0.1:${API_PORT};
        proxy_http_version  1.1;
        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;
        proxy_set_header    Connection        "";
        proxy_buffering     off;
        proxy_cache         off;
        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;
        proxy_connect_timeout  30s;
    }

    location = /api/v1/status/live {
        proxy_pass          http://127.0.0.1:${API_PORT};
        proxy_http_version  1.1;
        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;
        proxy_set_header    Connection        "";
        proxy_buffering     off;
        proxy_cache         off;
        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;
        proxy_connect_timeout  30s;
    }

    # API proxy (protected by both Nginx basic auth and API JWT auth)
    location /api/ {
        proxy_pass          http://127.0.0.1:${API_PORT};
        proxy_http_version  1.1;
        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;
        proxy_read_timeout    120s;
        proxy_send_timeout    120s;
        proxy_connect_timeout 30s;
    }

    # ── Health endpoint (no auth) ─────────────────────────────
    location /healthz {
        auth_basic off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
NGINX

# ─── Enable site ─────────────────────────────────────────────
ln -sf "$NGINX_AVAIL/$CONF_NAME" "$NGINX_ENABLED/$CONF_NAME"

# Remove nginx default site
[ -f "$NGINX_ENABLED/default" ] && rm -f "$NGINX_ENABLED/default" && echo "Removed nginx default site."

# ─── Test + reload ───────────────────────────────────────────
nginx -t
systemctl reload nginx
echo "Nginx reloaded."

echo ""
echo "======================================"
echo " [nginx-setup] HTTP ready."
echo " http://$SUBDOMAIN"
echo "======================================"
echo ""

# ─── Optional SSL via Let's Encrypt ──────────────────────────
if ! command -v certbot &>/dev/null; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot python3-certbot-nginx
fi

echo "Attempting SSL via Let's Encrypt..."
SERVER_IP="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null || echo 'unknown')"
DOMAIN_IP="$(getent hosts "$SUBDOMAIN" 2>/dev/null | awk '{print $1}' || echo 'unresolved')"

echo "  Server IP : $SERVER_IP"
echo "  Domain IP : $DOMAIN_IP"

if [ "$SERVER_IP" = "$DOMAIN_IP" ] && [ "$DOMAIN_IP" != "unresolved" ] && [ "$DOMAIN_IP" != "" ]; then
  echo "  DNS match confirmed — issuing certificate..."
  certbot --nginx \
    --non-interactive \
    --agree-tos \
    --register-unsafely-without-email \
    -d "$SUBDOMAIN" \
    --redirect \
    && echo "  SSL installed. https://$SUBDOMAIN is live." \
    || echo "  Certbot encountered an issue — HTTP still works."
else
  echo "  DNS not pointing here yet — skipping SSL."
  echo ""
  echo "  When DNS is ready, run:"
  echo "    certbot --nginx -d $SUBDOMAIN --redirect"
fi

# ─── Certbot auto-renewal cron ───────────────────────────────
echo "Configuring certbot auto-renewal..."
CERTBOT_CRON_TMP="/tmp/certbot_crontab"
crontab -l -u root 2>/dev/null \
  | grep -v "certbot renew" \
  > "$CERTBOT_CRON_TMP" || true

cat >> "$CERTBOT_CRON_TMP" <<CERTCRON

# ── certbot: renew certificates twice daily (recommended by Let's Encrypt) ──
0 3,15 * * * certbot renew --quiet --deploy-hook "systemctl reload nginx" 2>/dev/null
CERTCRON

crontab -u root "$CERTBOT_CRON_TMP"
rm -f "$CERTBOT_CRON_TMP"
echo "  Certbot renewal scheduled: 03:00 and 15:00 UTC daily."

echo ""
echo "======================================"
echo " [nginx-setup] done: ${SELLER_NAME}"
echo "======================================"
