#!/bin/bash
# =============================================================
# nginx-setup/nginx.sh
# Sets up Nginx reverse proxy with Basic Auth and optional SSL.
# Called by install.sh — all config via env vars.
# =============================================================
set -euo pipefail

SELLER_NAME="${SELLER_NAME:-seller1}"
CHROME_PORT="${CHROME_PORT:-3000}"
CHROME_USER="${CHROME_USER:-admin}"
CHROME_PASS="${CHROME_PASS:?CHROME_PASS is required}"
SUBDOMAIN="${SUBDOMAIN:?SUBDOMAIN is required}"

if ! [[ "$SELLER_NAME" =~ ^[a-z0-9][a-z0-9_-]{0,31}$ ]]; then
  echo "ERROR: SELLER_NAME must match ^[a-z0-9][a-z0-9_-]{0,31}$"
  exit 1
fi

if ! [[ "$CHROME_PORT" =~ ^[0-9]+$ ]] || (( CHROME_PORT < 1 || CHROME_PORT > 65535 )); then
  echo "ERROR: CHROME_PORT must be between 1 and 65535"
  exit 1
fi

if ! [[ "$SUBDOMAIN" =~ ^[A-Za-z0-9.-]+$ ]]; then
  echo "ERROR: SUBDOMAIN contains invalid characters"
  exit 1
fi

NGINX_AVAIL="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
CONF_NAME="${SELLER_NAME}-chrome"
HTPASSWD_DIR="/etc/nginx/htpasswd"
HTPASSWD_FILE="${HTPASSWD_DIR}/${SELLER_NAME}"

echo ""
echo "======================================"
echo " [nginx-setup] $SELLER_NAME"
echo " Subdomain : $SUBDOMAIN"
echo " Port      : $CHROME_PORT"
echo "======================================"
echo ""

# ─── Ensure nginx + apache2-utils installed ──────────────────
if ! command -v nginx &>/dev/null || ! command -v htpasswd &>/dev/null; then
  apt-get update -y -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nginx apache2-utils
fi
systemctl enable --now nginx

# ─── Basic Auth ──────────────────────────────────────────────
echo "Configuring Basic Auth..."
mkdir -p "$HTPASSWD_DIR"
htpasswd -cb "$HTPASSWD_FILE" "$CHROME_USER" "$CHROME_PASS"
chmod 640 "$HTPASSWD_FILE"
chown root:www-data "$HTPASSWD_FILE"

# ─── Nginx config ────────────────────────────────────────────
echo "Writing Nginx config → $NGINX_AVAIL/$CONF_NAME"
cat > "$NGINX_AVAIL/$CONF_NAME" <<NGINX
# ── ${SELLER_NAME} Chrome Browser VM ─────────────────────────
# Generated by chromium-fleet — do not edit manually.
# Subdomain : ${SUBDOMAIN}
# Port      : ${CHROME_PORT}

map \$http_upgrade \$connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${SUBDOMAIN};

    # ── Basic Auth ────────────────────────────────────────────
    auth_basic           "Chromium — ${SELLER_NAME}";
    auth_basic_user_file ${HTPASSWD_FILE};

    # ── Security headers ──────────────────────────────────────
    add_header X-Frame-Options          "SAMEORIGIN"                always;
    add_header X-Content-Type-Options   "nosniff"                   always;
    add_header X-XSS-Protection         "1; mode=block"             always;
    add_header Referrer-Policy          "no-referrer-when-downgrade" always;

    # ── Logging (per-seller) ─────────────────────────────────
    access_log /var/log/nginx/${SELLER_NAME}-chrome-access.log;
    error_log  /var/log/nginx/${SELLER_NAME}-chrome-error.log warn;

    # ── Proxy → Chromium (KasmVNC / noVNC WebSocket) ─────────
    location / {
        proxy_pass          http://127.0.0.1:${CHROME_PORT};

        proxy_http_version  1.1;
        proxy_set_header    Upgrade           \$http_upgrade;
        proxy_set_header    Connection        \$connection_upgrade;

        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;

        # Long timeouts for persistent WebSocket sessions
        proxy_read_timeout    3600s;
        proxy_send_timeout    3600s;
        proxy_connect_timeout   60s;

        proxy_buffering     off;
        proxy_buffer_size   128k;
        proxy_buffers       4 256k;
    }

    # ── Health endpoint (no auth) ─────────────────────────────
    location /healthz {
        auth_basic off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
NGINX

# ─── Enable site ─────────────────────────────────────────────
ln -sf "$NGINX_AVAIL/$CONF_NAME" "$NGINX_ENABLED/$CONF_NAME"

# Remove nginx default site
[ -f "$NGINX_ENABLED/default" ] && rm -f "$NGINX_ENABLED/default" && echo "Removed nginx default site."

# ─── Test + reload ───────────────────────────────────────────
nginx -t
systemctl reload nginx
echo "Nginx reloaded."

echo ""
echo "======================================"
echo " [nginx-setup] HTTP ready."
echo " http://$SUBDOMAIN"
echo "======================================"
echo ""

# ─── Optional SSL via Let's Encrypt ──────────────────────────
if ! command -v certbot &>/dev/null; then
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot python3-certbot-nginx
fi

echo "Attempting SSL via Let's Encrypt..."
SERVER_IP="$(curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null || echo 'unknown')"
DOMAIN_IP="$(getent hosts "$SUBDOMAIN" 2>/dev/null | awk '{print $1}' || echo 'unresolved')"

echo "  Server IP : $SERVER_IP"
echo "  Domain IP : $DOMAIN_IP"

if [ "$SERVER_IP" = "$DOMAIN_IP" ] && [ "$DOMAIN_IP" != "unresolved" ] && [ "$DOMAIN_IP" != "" ]; then
  echo "  DNS match confirmed — issuing certificate..."
  certbot --nginx \
    --non-interactive \
    --agree-tos \
    --register-unsafely-without-email \
    -d "$SUBDOMAIN" \
    --redirect \
    && echo "  SSL installed. https://$SUBDOMAIN is live." \
    || echo "  Certbot encountered an issue — HTTP still works."
else
  echo "  DNS not pointing here yet — skipping SSL."
  echo ""
  echo "  When DNS is ready, run:"
  echo "    certbot --nginx -d $SUBDOMAIN --redirect"
fi

echo ""
echo "======================================"
echo " [nginx-setup] done: ${SELLER_NAME}"
echo "======================================"
